MKPATH=../../../mk/
include $(MKPATH)buildsys.mk

DATA = store/credits.txt \
	store/alchemy.ogg0 \
	store/magic.ogg0 \
	store/meow.ogg \
	store/purr.ogg0 \
    outside/rain_light.ogg \
    store/shop_spells.ogg0 \
	store/alchemy.mp3 \
	store/magic.mp3 \
	store/meow.mp3 \
	store/purr.mp3 \
    outside/rain_light.mp3 \
    store/shop_spells.mp3 \
    voice/intro_1 \
    voice/intro_2 \
    voice/intro_3 \
    voice/intro_4 \
    voice/intro_5 \
    voice/intro_6 \
    voice/intro_7

PACKAGE = sounds/ambient
