MKPATH=../../../mk/
include $(MKPATH)buildsys.mk

DATA = store/credits.txt \
	store/alchemy.ogg0 \
	store/magic.ogg0 \
	store/meow.ogg \
	store/purr.ogg0 \
    outside/rain_light.ogg \
	store/alchemy.mp3 \
	store/magic.mp3 \
	store/meow.mp3 \
	store/purr.mp3 \
    outside/rain_light.mp3

PACKAGE = sounds/ambient
