MKPATH=../../../mk/
include $(MKPATH)buildsys.mk

DATA = store/credits.txt \
    store/alchemy.ogg0 \
    store/alchemy.mp3 \
    store/magic.ogg0 \
    store/magic.mp3 \
    store/meow.ogg \
    store/meow.mp3 \
    store/purr.ogg0 \
    store/purr.mp3 \
    store/shop_spells.ogg0 \
    store/shop_spells.mp3 \
    outside/rain_light.ogg \
    outside/rain_light.mp3 \
    voice/intro_1.ogg \
    voice/intro_1.mp3 \
    voice/intro_2.ogg \
    voice/intro_2.mp3 \
    voice/intro_3.ogg \
    voice/intro_3.mp3 \
    voice/intro_4.ogg \
    voice/intro_4.mp3 \
    voice/intro_5.ogg \
    voice/intro_5.mp3 \
    voice/intro_6.ogg \
    voice/intro_6.mp3 \
    voice/intro_7.ogg \
    voice/intro_7.mp3

PACKAGE = sounds/ambient
