/*
 * File: list-message.h
 * Purpose: List of message types
 *
 * sound - the name of the entry in sound.prf
 */

/* id */
MSG(GENERIC, "")
MSG(RED_INK, "red_ink") // only text color
MSG(SILENT, "silent")
MSG(SILENT0, "silent0")
MSG(SILENT100, "silent100")
MSG(SILENT101, "silent101")
MSG(HIT, "hit")
MSG(HIT_BLADE, "hit_blade")
MSG(HIT_MACE, "hit_mace")
MSG(HIT_WHIP, "hit_whip")
MSG(MISS, "miss")
MSG(SHOOT_MISS, "shoot_miss")
MSG(FLEE, "flee")
MSG(DROP, "drop")
MSG(DROP_IN_HOUSE, "drop_in_house")
MSG(KILL, "kill")
MSG(LEVEL, "level")
MSG(DEATH, "death")
MSG(STUDY, "study")
MSG(TELEPORT, "teleport")
MSG(PHASE_DOOR, "phase_door")
MSG(SHOOT, "shoot")
MSG(SHOOT_GOOD, "shoot_good")
MSG(SHOOT_GREAT, "shoot_great")
MSG(SHOOT_SUPERB, "shoot_superb")
MSG(SHOOT_BOW, "shoot_bow")
MSG(SHOOT_CROSSBOW, "shoot_crossbow")
MSG(SHOOT_SLING, "shoot_sling")
MSG(SHOOT_BOOMERANG, "shoot_boomerang")
MSG(THROWN, "thrown")
MSG(QUAFF, "quaff")
MSG(ZAP_ROD, "zap_rod")
MSG(WALK, "walk")
MSG(TPOTHER, "tpother")
MSG(HITWALL, "hitwall")
MSG(EAT, "eat")
MSG(STORE1, "store1")
MSG(STORE2, "store2")
MSG(STORE3, "store3")
MSG(STORE4, "store4")
MSG(DIG, "dig")
MSG(DIG_TREASURE, "dig_treasure")
MSG(OPENDOOR, "opendoor")
MSG(SHUTDOOR, "shutdoor")
MSG(DOOR_CLOSED, "door_closed")
MSG(TPLEVEL, "tplevel")
MSG(BELL, "bell")
MSG(NOTHING_TO_OPEN, "nothing_to_open")
MSG(LOCKPICK_FAIL, "lockpick_fail")
MSG(STAIRS_DOWN, "stairs_down")
MSG(HITPOINT_WARN, "hitpoint_warn")
MSG(ACT_ARTIFACT, "act_artifact")
MSG(USE_STAFF, "use_staff")
MSG(DESTROY, "destroy")
MSG(DESTROY_POTION, "destroy_potion")
MSG(BURN, "burn")
MSG(MON_HIT, "mon_hit")
MSG(MON_TOUCH, "mon_touch")
MSG(MON_PUNCH, "mon_punch")
MSG(MON_KICK, "mon_kick")
MSG(MON_CLAW, "mon_claw")
MSG(MON_BITE, "mon_bite")
MSG(MON_STING, "mon_sting")
MSG(MON_BUTT, "mon_butt")
MSG(MON_CRUSH, "mon_crush")
MSG(MON_ENGULF, "mon_engulf")
MSG(MON_CRAWL, "mon_crawl")
MSG(MON_DROOL, "mon_drool")
MSG(MON_SPIT, "mon_spit")
MSG(MON_GAZE, "mon_gaze")
MSG(MON_WAIL, "mon_wail")
MSG(MON_SPORE, "mon_spore")
MSG(MON_BEG, "mon_beg")
MSG(MON_INSULT, "mon_insult")
MSG(MON_MOAN, "mon_moan")
MSG(MON_HYPNOTIZE, "mon_hypnotize")
MSG(MON_SWALLOW, "mon_swallow")
MSG(MON_DEVOUR, "mon_devour")
MSG(RECOVER, "recover")
MSG(BLIND, "blind")
MSG(CONFUSED, "confused")
MSG(POISONED, "poisoned")
MSG(AFRAID, "afraid")
MSG(PARALYZED, "paralyzed")
MSG(DRUGGED, "drugged")
MSG(SPEED, "speed")
MSG(SLOW, "slow")
MSG(SHIELD, "shield")
MSG(BLESSED, "blessed")
MSG(HERO, "hero")
MSG(BERSERK, "berserk")
MSG(BOLD, "bold")
MSG(PROT_EVIL, "prot_evil")
MSG(INVULN, "invuln")
MSG(SEE_INVIS, "see_invis")
MSG(INFRARED, "infrared")
MSG(RES_ACID, "res_acid")
MSG(RES_ELEC, "res_elec")
MSG(RES_FIRE, "res_fire")
MSG(RES_COLD, "res_cold")
MSG(RES_POIS, "res_pois")
MSG(STUN, "stun")
MSG(CUT, "cut")
MSG(STAIRS_UP, "stairs_up")
MSG(STORE_ENTER, "store_enter")
MSG(STORE_LEAVE, "store_leave")
MSG(STORE_HOME, "store_home")
MSG(STORE_HOME_CUCKOO, "store_home_cuckoo")
MSG(STORE_OTHER_SOUND, "store_other_sound")
MSG(STORE_GENERAL_SOUND, "store_general_sound")
MSG(STORE_TEMPLE, "store_temple")
MSG(STORE_BOOKSELLER, "store_bookseller")
MSG(STORE_B_MARKET_SOUND, "store_b_market_sound")
MSG(STORE_XBM_SOUND, "store_xbm_sound")
MSG(STORE_HOME_SOUND, "store_home_sound")
MSG(STORE_PLAYER_SOUND, "store_player_sound")
MSG(STORE_ALCHEMY, "store_alchemy")
MSG(STORE_ALCHEMY_BOOM, "store_alchemy_boom")
MSG(STORE_MAGIC_TOWER, "store_magic_tower")
MSG(STORE_SPELLS, "store_spells")
MSG(TAVERN, "tavern")
MSG(NPC_ARMOR, "npc_armor")
MSG(NPC_ARROW, "npc_arrow")
MSG(STORE_MAGIC, "store_magic")
MSG(STORE_WEAPON, "store_weapon")

MSG(NPC_CAT, "npc_cat")
MSG(NPC_HI, "npc_hi")
MSG(NPC_GIRL, "npc_girl")
MSG(NPC_WARR, "npc_warr")
MSG(NPC_WELCOME, "npc_welcome")
MSG(NPC_VET, "npc_vet")
MSG(NPC_ROUGH, "npc_rough")
MSG(NPC_BELCH, "npc_belch")
MSG(NPC_ROSE, "npc_rose")
MSG(NPC_DRUNK, "npc_drunk")
MSG(NPC_DUEL, "npc_duel")
MSG(NPC_MARTA, "npc_marta")
MSG(NPC_CAIN, "npc_cain")
MSG(NPC_TOM, "npc_tom")

MSG(GOLD_1, "gold_1")
MSG(GOLD_2, "gold_2")
MSG(GOLD_3, "gold_3")
MSG(MONEY1, "money1")
MSG(MONEY2, "money2")
MSG(MONEY3, "money3")
MSG(SHOOT_HIT, "shoot_hit")
MSG(STORE5, "store5")
MSG(LOCKPICK, "lockpick")
MSG(OPEN_CHEST, "open_chest")
MSG(DISARM, "disarm")
MSG(IDENT_BAD, "identify_bad")
MSG(IDENT_EGO, "identify_ego")
MSG(IDENT_ART, "identify_art")
MSG(BR_ELEMENTS, "breathe_elements")
MSG(BR_FROST, "breathe_frost")
MSG(BR_ELEC, "breathe_elec")
MSG(BR_ACID, "breathe_acid")
MSG(BR_GAS, "breathe_gas")
MSG(BR_FIRE, "breathe_fire")
MSG(BR_WATE, "breathe_water")
MSG(BR_DISEN, "breathe_disenchant")
MSG(BR_CHAOS, "breathe_chaos")
MSG(BR_SHARDS, "breathe_shards")
MSG(BR_SOUND, "breathe_sound")
MSG(BR_LIGHT, "breathe_light")
MSG(BR_DARK, "breathe_dark")
MSG(BR_NETHER, "breathe_nether")
MSG(BR_NEXUS, "breathe_nexus")
MSG(BR_TIME, "breathe_time")
MSG(BR_INERTIA, "breathe_inertia")
MSG(BR_GRAVITY, "breathe_gravity")
MSG(BR_PLASMA, "breathe_plasma")
MSG(BR_FORCE, "breathe_force")
MSG(SUM_MONSTER, "summon_monster")
MSG(SUM_AINU, "summon_ainu")
MSG(SUM_ANGEL, "summon_angel")
MSG(SUM_UNDEAD, "summon_undead")
MSG(SUM_ANIMAL, "summon_animal")
MSG(SUM_SPIDER, "summon_spider")
MSG(SUM_HOUND, "summon_hound")
MSG(SUM_HYDRA, "summon_hydra")
MSG(SUM_DEMON, "summon_demon")
MSG(SUM_DRAGON, "summon_dragon")
MSG(SUM_HI_UNDEAD, "summon_gr_undead")
MSG(SUM_HI_DRAGON, "summon_gr_dragon")
MSG(SUM_HI_DEMON, "summon_gr_demon")
MSG(SUM_WRAITH, "summon_ringwraith")
MSG(SUM_UNIQUE, "summon_unique")
MSG(WIELD, "wield")
MSG(QUIVER, "quiver")
MSG(CURSED, "cursed")
MSG(RUNE, "rune")
MSG(HUNGRY, "hungry")
MSG(NOTICE, "notice")
MSG(TOWN, "town")
MSG(TOWN_RARE, "town_rare")
MSG(AMBIENT_DAY, "ambient_day")
MSG(AMBIENT_NITE, "ambient_nite")
MSG(AMBIENT_DNG1, "ambient_dng1")
MSG(AMBIENT_DNG2, "ambient_dng2")
MSG(AMBIENT_DNG3, "ambient_dng3")
MSG(AMBIENT_DNG4, "ambient_dng4")
MSG(AMBIENT_DNG5, "ambient_dng5")
MSG(ENTER_RUINS, "enter_ruins")
MSG(PATHS_OF_THE_DEAD, "paths_of_the_dead")
MSG(MANOR, "manor")
MSG(ENTER_BARROW, "enter_barrow")
MSG(ORC_CAVES, "orc_caves")
MSG(CREATE_TRAP, "mon_create_trap")
MSG(SHRIEK, "mon_shriek")
MSG(CAST_FEAR, "mon_cast_fear")
MSG(HIT_GOOD, "hit_good")
MSG(HIT_GREAT, "hit_great")
MSG(HIT_SUPERB, "hit_superb")
MSG(HIT_HI_GREAT, "hit_hi_great")
MSG(HIT_HI_SUPERB, "hit_hi_superb")
MSG(SPELL, "cast_spell")
MSG(BALL, "ball")
MSG(BOLT, "bolt")
MSG(DAMAGE, "damage")
MSG(EARTHQUAKE, "earthquake")
MSG(DESTRUCTION, "destruction")
MSG(BLAST, "blast")
MSG(BEAM, "beam")
MSG(ARC, "arc")
MSG(STRIKE, "strike")
MSG(LASH, "lash")
MSG(MELEE_BLOWS, "melee_blows")
MSG(PROJECT, "project")
MSG(SPOT, "spot")
MSG(STAR, "star")
MSG(TOUCH, "touch")
MSG(CREATE_WALLS, "create_walls")
MSG(CREATE_TREES, "create_trees")
MSG(DETECT, "detect")
MSG(GLYPH, "glyph")
MSG(PRAYER, "pray_prayer")
MSG(KILL_UNIQUE, "kill_unique")
MSG(KILL_KING, "kill_king")
MSG(KILL_NAZGUL, "kill_nazgul")
MSG(KILL_UNIQUE_UNDEAD, "kill_unique_undead")
MSG(KILL_UNIQUE_DEMON, "kill_unique_demon")
MSG(KILL_UNIQUE_DRAGON, "kill_unique_dragon")
MSG(KILL_UNIQUE_YAGA, "kill_unique_yaga")
MSG(KILL_UNIQUE_KIKIMORA, "kill_unique_kikimora")
MSG(KILL_UNIQUE_WITCH_KING, "kill_unique_witch_king")
MSG(KILL_UNIQUE_SHELOB, "kill_unique_shelob")
MSG(DEFEAT_UNIQUE_SHTUKENSIA, "defeat_unique_shtukensia")
MSG(KILL_UNIQUE_ANGEL, "kill_unique_angel")
MSG(KILL_KOSCHEI, "kill_koschei")
MSG(KILL_YEEK,"kill_yeek")
MSG(KILL_RODENT,"kill_rodent")
MSG(KILL_INSECT,"kill_insect")
MSG(KILL_SNAKE,"kill_snake")
MSG(KILL_HYDRA,"kill_hydra")
MSG(KILL_SLIME,"kill_slime")
MSG(KILL_STINGER,"kill_stinger")
MSG(KILL_MUSHROOM,"kill_mushroom")
MSG(DRAIN_STAT, "drain_stat")
MSG(MULTIPLY, "multiply")
MSG(SCRAMBLE, "scramble")
MSG(WILD_RAIN, "wild_rain")
MSG(WILD_WAVES, "wild_waves")
MSG(WILD_RIVER, "wild_river")
MSG(WILD_WASTE, "wild_waste")
MSG(WILD_VOLCANO, "wild_volcano")
MSG(WILD_GRASS, "wild_grass")
MSG(WILD_WOOD, "wild_wood")
MSG(WILD_MOUNTAIN, "wild_mountain")
MSG(WILD_DESERT, "wild_desert")
MSG(WILD_GLACIER, "wild_glacier")
MSG(WILD_SWAMP, "wild_swamp")
MSG(WILD_DEEPWATER, "wild_deepwater")
MSG(WILD_HILL, "wild_hill")
MSG(WILD_SHORE, "wild_shore")
MSG(AMBIENT_SAURON, "ambient_sauron")
MSG(AMBIENT_MORGOTH, "ambient_morgoth")
MSG(AMBIENT_DNG6, "ambient_dng6")
MSG(AMBIENT_SENYA, "ambient_senya")
MSG(AMBIENT_XAKAZE, "ambient_xakaze")
MSG(AMBIENT_MELKOR, "ambient_melkor")
MSG(HIT_HI_CRITICAL, "hit_hi_critical")
MSG(ENTER_PIT, "enter_pit")
MSG(TRAP_SETOFF, "trap_setoff")
MSG(TRAP_SETOFF_FLOOR, "trap_setoff_floor")
MSG(UNAFFECTED, "unaffected")
MSG(IMMUNE, "immune")
MSG(RESIST_A_LOT, "resist_a_lot")
MSG(RESIST, "resist")
MSG(RESIST_SOMEWHAT, "resist_somewhat")
MSG(SPELL_FAIL, "spell_fail")
MSG(HOWL, "werewolf_howl")
MSG(IMP, "imp_giggles")
MSG(TERRAIN_SLIP, "terrain_slip")
MSG(TUNNEL_WALL, "tunnel_wall")
MSG(CHOP_TREE, "chop_tree")
MSG(CHOP_TREE_FALL, "chop_tree_fall")
MSG(SENTRY, "sentry")
MSG(DOOR_BROKEN, "door_broken")
MSG(DISRUPT, "disrupt")
MSG(DISARM_WEAPON, "disarm_weapon")
MSG(PUNCH, "punch")
MSG(ITEM_BLADE,"item_blade")
MSG(ITEM_WHIP,"item_whip")
MSG(ITEM_WOOD,"item_wood")
MSG(ITEM_LIGHT_ARMOR,"item_light_armor")
MSG(ITEM_MEDIUM_ARMOR,"item_medium_armor")
MSG(ITEM_HEAVY_ARMOR,"item_heavy_armor")
MSG(ITEM_RING,"item_ring")
MSG(ITEM_AMULET,"item_amulet")
MSG(ITEM_PICKUP,"item_pickup")
MSG(DROP_GOLD,"drop_gold")
MSG(ITEM_TAKEOFF_TINY,"item_takeoff_tiny")
MSG(ITEM_TAKEOFF_SMALL,"item_takeoff_small")
MSG(ITEM_TAKEOFF_MEDIUM,"item_takeoff_medium")
MSG(ITEM_TAKEOFF_LARGE,"item_takeoff_large")
MSG(ITEM_LIGHT_TORCH,"item_light_torch")
MSG(ITEM_LIGHT_LANTERN,"item_light_lantern")
MSG(ITEM_LIGHT_LAMP,"item_light_lamp")
MSG(ITEM_LIGHT_PHIAL,"item_light_phial")
MSG(ITEM_LIGHT_PALANTIR,"item_light_palantir")
MSG(AMBIENT_VOICE,"ambient_voice")
MSG(KIKIMORA,"kikimora")
MSG(GONG,"gong")
MSG(FANFARE,"fanfare")
MSG(POLY_BAT,"poly_bat")
MSG(MESSAGE, "message")
MSG(DANGER_9, "danger_9")
MSG(BALANCED_STANCE, "balanced_stance")
MSG(DEFENSIVE_STANCE, "defensive_stance")
MSG(OFFENSIVE_STANCE, "offensive_stance")
MSG(WILD_RAIN_LIGHT, "wild_rain_light")
MSG(WILD_THUNDER_LIGHT, "wild_thunder_light")
MSG(WILD_THUNDER, "wild_thunder")


// client T sounds
MSG(BROWSE_BOOK, "browse_book")

// music-ambience
MSG(SEWERS1, "sewers1")
MSG(SEWERS2, "sewers2")
MSG(SEWERS3, "sewers3")
MSG(SEWERS4, "sewers4")
MSG(SEWERS5, "sewers5")
MSG(SEWERS6, "sewers6")

/* Max message index (sound) */
MSG(MAX, NULL)

/* PWMAngband-specific: internal messages broadcast to all players */
MSG(BROADCAST_ENTER_LEAVE, NULL)
MSG(BROADCAST_DIED, NULL)
MSG(BROADCAST_WON, NULL)
MSG(BROADCAST_ARENA, NULL)
MSG(BROADCAST_QUEST, NULL)
MSG(BROADCAST_LEVEL, NULL)
MSG(BROADCAST_FRUITBAT, NULL)
MSG(BROADCAST_KILL_UNIQUE, NULL)
MSG(BROADCAST_KILL_KING, NULL)
MSG(BROADCAST_STORE, NULL)

/* PWMAngband-specific */
MSG(HOSTILE, NULL)
MSG(DIED, NULL)
MSG(VERSION, NULL)
MSG(MOTD, NULL)

/* MAngband-specific */
MSG(TALK, NULL)
MSG(YELL, NULL)
MSG(SOCIAL, NULL)
MSG(PY_SPELL, NULL)
MSG(PY_PRAYER, NULL)
MSG(PY_MISC, NULL)
MSG(MON_OTHER, NULL)

/* Client-side and system messages */
MSG(LOCAL, NULL)
MSG(WHISPER, NULL)
MSG(CHAT, NULL)

/* Max message index (message) */
MSG(MAX_PARSE, NULL)
